#!/bin/bash
readonly LNG=${1:-en_US}
readonly URL="http://www.google.com/speech-api/v1/recognize?lang=$LNG&client=chromium"

arecord $2 -r16000 -c2 -f S16_LE -t wav voice.wav 2>/dev/null
trap 'rm -f voice.flac' EXIT 
flac -o voice.flac \
    --sample-rate=16000 \
    --channels=2 \
    --bps=16 \
    --endian=little \
    --delete-input-file voice.wav 2>/dev/null
echo "okay." | text-to-speech
ret="$(curl -s -A Mozilla \
    --data-binary @voice.flac \
    --header 'Content-Type: audio/x-flac; rate=16000;' "$URL" \
    | jshon -e hypotheses -e 0 -e utterance -u 2>/dev/null)"
if [ "$ret" != "" ]; then
    echo "$ret"
else
    echo "cannot recognize"
fi

