#!/bin/bash

readonly LNG=${1:-en_US}
readonly DELAY=${2:-4}
[[ "$DELAY" =~ [0-9]+ ]] || exit 1
readonly URL="http://www.google.com/speech-api/v1/recognize?lang=${LNG}&client=chromium"
readonly STOCK="${HOME}/.${0##*/}"
readonly HEADER='Content-Type: audio/x-flac; rate=16000;'

trap 'rm -f "${STOCK}.flac"' EXIT
arecord -t wav -d "$DELAY" "${STOCK}.wav" -r 16000 &>/dev/null
flac -o "${STOCK}.flac" --delete-input-file "${STOCK}.wav" &>/dev/null
ret="$(curl -s -A Mozilla --data-binary "@${STOCK}.flac" --header "$HEADER"  "$URL" | \
    jshon -e hypotheses -e 0 -e utterance -u 2>/dev/null)"
if [ "$ret" != "" ]; then
    echo "$ret"
else
    echo "cannot recognize"
fi

