#!/bin/bash

readonly LNG=${1:-en_US}
readonly URL="http://translate.google.com/translate_tts?ie=UTF-8&tl=$LNG&q="

urlencode() {
    perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$*"
}

while read -n 100 -r chunk; do
    mpg123 "$URL$(urlencode $chunk)" 2>/dev/null
done </dev/stdin
