#!/bin/bash

readonly LNG=${1:-en_US}
readonly URL="http://translate.google.com/translate_tts?ie=UTF-8&tl=${LNG}&q="
readonly STOCK="${HOME}/.${0##*/}"

read_stdin() {
    cat /dev/stdin 
}

urlencode() {
    /usr/bin/env python2 <<EOF
# coding=utf-8
import urllib, sys
words='''$1'''.split()
line=""
for word in words:
    word+=" "
    if len(word) + len(line) >= 100:
        sys.stdout.write(urllib.quote(line) + ' ')
        line=word
    else:
        line+=word
sys.stdout.write(urllib.quote(line))
EOF
}

which mpg123 &>/dev/null || {
echo "error: mpg123 not installed"
exit 1
}

which curl &>/dev/null || {
echo "error: curl not installed"
exit 1
}

trap "rm -f $STOCK" EXIT
for chunk in $(urlencode "$(read_stdin)"); do
    curl -s -A Mozilla -o "$STOCK" "${URL}${chunk}"
    mpg123 "$STOCK" &>/dev/null
done
