#!/bin/bash
echo "any task" | text-to-speech
res="$(speech-to-text en_US -d3)" 
echo "$res"
case "$res" in
    Facebook)
        echo "I will open facebook for you" | text-to-speech
        xdg-open "http://facebook.com/"
        ;;
    *mail)
        echo "I will open gmail for you" | text-to-speech
        xdg-open "http://gmail.com/"
        ;;
    say*)
        word="$(cut -d ' ' -f 2- <<<"$res")"
        echo "$word from $(whoami) $(hostname)" | text-to-speech
        ;;
    "cannot recognize")
        echo ignored | text-to-speech
        ;;
    where*)
        word="$(cut -d ' ' -f 3- <<<"$res")"
        echo "searching location for $word" | text-to-speech
        xdg-open "http://maps.google.com/maps?q=$word"
        ;;
    *)
        echo "I am searching $res on google" | text-to-speech
        xdg-open "http://www.google.com/search?btnG=1&pws=0&q=$res"
        ;;
esac
