#!/bin/bash
text-to-speech <<<"any task"
res="$(speech-to-text en_US -d5)" 
echo "$res"
case "$res" in
    Facebook)
        text-to-speech <<<"I will open facebook for you"
        xdg-open "http://facebook.com/"
        ;;
    Gmail)
        text-to-speech <<<"I will open gmail for you"
        xdg-open "http://gmail.com/"
        ;;
    say*)
        word="$(cut -d ' ' -f 2- <<<"$res")"
        text-to-speech <<<"$word from $(whoami) $(hostname)"
        ;;
    "cannot recognize")
        text-to-speech <<<"I dont know what you mean"
        ;;
    "where is"*)
        word="$(cut -d ' ' -f 3- <<<"$res")"
        text-to-speech <<<"searching location for $word"
        xdg-open "http://maps.google.com/maps?q=$word"
        ;;
    *)
        text-to-speech <<<"I am searching $res on google"
        xdg-open "http://www.google.com/search?btnG=1&pws=0&q=$res"
        ;;
esac
